### ISSUE TITLE
Ubuntu 14.04 build errors

### ISSUE THREAD

**Issue by cholcombe973** [FauxFaux/apt-pkg-native-rs#2]
I could be wrong but it looks like this won't build on 14.04 ubuntu amd64.  I'm testing in a docker container and I'm getting no member found errors:
```
process didn't exit successfully: `/build/target/release/build/apt-pkg-native-78b23c663c8114ea/build-script-build` (exit code: 101)
--- stdout
cargo:rerun-if-changed=apt-pkg-c/lib.cpp
TARGET = Some("x86_64-unknown-linux-gnu")
OPT_LEVEL = Some("3")
TARGET = Some("x86_64-unknown-linux-gnu")
HOST = Some("x86_64-unknown-linux-gnu")
TARGET = Some("x86_64-unknown-linux-gnu")
TARGET = Some("x86_64-unknown-linux-gnu")
HOST = Some("x86_64-unknown-linux-gnu")
CXX_x86_64-unknown-linux-gnu = None
CXX_x86_64_unknown_linux_gnu = None
HOST_CXX = None
CXX = None
HOST = Some("x86_64-unknown-linux-gnu")
TARGET = Some("x86_64-unknown-linux-gnu")
HOST = Some("x86_64-unknown-linux-gnu")
CXXFLAGS_x86_64-unknown-linux-gnu = None
CXXFLAGS_x86_64_unknown_linux_gnu = None
HOST_CXXFLAGS = None
CXXFLAGS = None
DEBUG = Some("false")
running: "c++" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-m64" "-std=gnu++11" "-Wall" "-Wextra" "-o" "/build/target/release/build/apt-pkg-native-5b278d76fd822a27/out/apt-pkg-c/lib.o" "-c" "apt-pkg-c/lib.cpp"
cargo:warning=apt-pkg-c/lib.cpp:231:30: error: no member named 'SourcePkgName' in 'pkgCache::VerIterator'
cargo:warning=    return wrapper->iterator.SourcePkgName();
cargo:warning=           ~~~~~~~~~~~~~~~~~ ^
cargo:warning=apt-pkg-c/lib.cpp:235:30: error: no member named 'SourceVerStr' in 'pkgCache::VerIterator'
cargo:warning=    return wrapper->iterator.SourceVerStr();
cargo:warning=           ~~~~~~~~~~~~~~~~~ ^
cargo:warning=apt-pkg-c/lib.cpp:245:53: error: no matching member function for call to 'GetPriority'
cargo:warning=    return wrapper->cache->cache_file->GetPolicy()->GetPriority(wrapper->iterator);
cargo:warning=           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~
cargo:warning=/usr/include/apt-pkg/policy.h:82:25: note: candidate function not viable: no known conversion from 'pkgCache::VerIterator' to 'const pkgCache::PkgIterator' for 1st argument
cargo:warning=   virtual signed short GetPriority(pkgCache::PkgIterator const &Pkg);
cargo:warning=                        ^
cargo:warning=/usr/include/apt-pkg/policy.h:83:25: note: candidate function not viable: no known conversion from 'pkgCache::VerIterator' to 'const pkgCache::PkgFileIterator' for 1st argument
cargo:warning=   virtual signed short GetPriority(pkgCache::PkgFileIterator const &File);
cargo:warning=                        ^
cargo:warning=3 errors generated.
exit code: 1

--- stderr
thread 'main' panicked at '

Internal error occurred: Command "c++" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-m64" "-std=gnu++11" "-Wall" "-Wextra" "-o" "/build/target/release/build/apt-pkg-native-5b278d76fd822a27/out/apt-pkg-c/lib.o" "-c" "apt-pkg-c/lib.cpp" with args "c++" did not execute successfully (status code exit code: 1).
```

My guess is that I'm not using the right min version but I don't know what that should be.

**Comment by FauxFaux** [comment]
The first bit of data isn't available in Trusty's version of apt; it's not even computed:
https://github.com/Debian/apt/commit/a221efc331693f8905da870141756c892911c433

The second is there, but not exposed (which means):
https://github.com/Debian/apt/commit/9fb02ab02528ea45747318af26fae8a732cd2840#diff-0c92f95f49f860ef2cb1d552e179f47eR324

I could.. do a feature flag that allows compilation with the older apt, and doesn't expose that info?

I wouldn't advise trying to upgrade `apt` on Trusty.

**Comment by FauxFaux** [comment]
It appears the build passes on Trusty on Travis as Travis is helpfully backporting apt for us:
https://travis-ci.org/FauxFaux/apt-pkg-native-rs/jobs/314351920#L444

**Comment by FauxFaux** [comment]
That commit works for me inside a Trusty docker container. Build with:

```
cargo build --features ye-olde-apt
```

Does that help? If so, I'll do a release.

**Comment by cholcombe973** [comment]
haha  alright i'll give it a try.  I'll post back soon :)
